### ISSUE TITLE
'move_in_below' declared but not implemented

### ISSUE THREAD

**Issue by libreliu** [kpeeters/tree.hh#1]
Thanks a lot for the tree library.
I noticed that 'move_in_below' is declared but seems not to be implemented, but it's in the doc.
It took me for a while to figure out what was really happening, lol.

(I think 'move_in' also works in my situation, and I'm just sending this for a reminder)

**Comment by kpeeters** [comment]
Now fixed with commit edb44045df64efd72dc0dab97388915641987acd .
