### ISSUE TITLE
"byte" is ambiguous (C++17)

### ISSUE THREAD

**Issue by Alvazz** [kpeeters/tree.hh#23]
"byte" is ambiguous C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\rpcndr.h

**Comment by kpeeters** [comment]
I am not sure what you mean, the `tree.hh` file does not contain the word `byte` except in a comment. Moreover, it's hardly ambiguous.

**Comment by Alvazz** [comment]
![image](https://github.com/kpeeters/tree.hh/assets/50744096/5e593fce-1428-43a2-8ede-7f9ce8bb3d59)

**Comment by Alvazz** [comment]
![image](https://github.com/kpeeters/tree.hh/assets/50744096/68b6e94b-e1a8-4ad1-b8c2-67874d40143a)

**Comment by kpeeters** [comment]
None of those lines refer to `tree.hh`, are you sure you are posting in the correct repository?
