### ISSUE TITLE
"C++17 deprecation" warnings when compiling under VS2019

### ISSUE THREAD

**Issue by hals1010** [kpeeters/tree.hh#3]
I cannot compile tree.hh under VS2019 and ISO C++17 Standard (/std:c++17):

Severity	Code	Description	Project	File	Line	Suppression State
Error	C4996	'std::allocator<tree_node_<T>>::destroy': warning STL4010: Various members of std::allocator are deprecated in C++17. Use std::allocator_traits instead of accessing these members directly. You can define _SILENCE_CXX17_OLD_ALLOCATOR_MEMBERS_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.	3DView	C:\HamburgSVN\CurryWin\C100\include\tree.hh	566	

(8 errors in total)

Regards,
Jörn

**Comment by kpeeters** [comment]
I have pushed what is hopefully a fix to the master branch; can you please try again (I do not use VS myself and clang++-10 does not (yet) produce that warning).

**Comment by hals1010** [comment]
Hi Kasper,

yes, this did the trick - thanks for your quick fix!

Best,
Jörn
