### ISSUE TITLE
segfault inside move operator=

### ISSUE THREAD

**Issue by luxe** [kpeeters/tree.hh#4]
I'm trying to understand the logic of the move assignment operator, because I'm experiencing a segfault annotated below:  
```
template <class T, class tree_node_allocator>
tree<T,tree_node_allocator>& tree<T, tree_node_allocator>::operator=(tree<T, tree_node_allocator>&& x)
	{
	if(this != &x) {
		clear(); // clear any existing data.
		
		head->next_sibling=x.head->next_sibling;
		feet->prev_sibling=x.head->prev_sibling;
		x.head->next_sibling->prev_sibling=head;
		x.feet->prev_sibling->next_sibling=feet; // <- SEGFAULT
		x.head->next_sibling=x.feet;
		x.feet->prev_sibling=x.head;
		}
	return *this;
	}
```
The pointer swaps are identical to the move constructor.
In my case, the tree that was already constructed and being moved has `x.feet->prev_sibling` null,  
leaving `x.feet->prev_sibling->next_sibling=feet;` undefined behavior.

I've tried different things like skipping when its null or allocating for `x.feet->prev_sibling` when null but this causes crashes later when calculating depth.  Let me know if anything stands out to you.  I'll need to make a minimal example and visualize the pointer swaps.  I've also replaced the move implementation with the copy version:  
```
template <class T, class tree_node_allocator>
tree<T,tree_node_allocator>& tree<T, tree_node_allocator>::operator=(const tree<T, tree_node_allocator>& other)
	{
	if(this != &other)
		copy_(other);
	return *this;
	}
```
and this solved all my problems but obviously not taking advantage of move optimizations.

**Comment by kpeeters** [comment]
> In my case, the tree that was already constructed and being moved has x.feet->prev_sibling null,

That's not supposed to happen. Do you have a minimal example that you can share?

**Comment by luxe** [comment]
I've simplified a little further.  ([example.zip](https://github.com/kpeeters/tree.hh/files/5449272/example.zip))

For context,  I'm serializing a tree to/from disk.  
In order to achieve that, I convert the tree into a `std::vector<std::pair<int,T>>` and then serialize it with [nlohmann::json](https://github.com/nlohmann/json).

I've made 1 adjustment to `tree.hh` for debugging purposes.  I've added these into the move assignment:  
```
if (x.head->next_sibling == nullptr){std::cout << "NULL HEAD" << std::endl;}else { std::cout << "GOOD HEAD" << std::endl; }
if (x.feet->prev_sibling == nullptr){std::cout << "NULL FEET" << std::endl;}else { std::cout << "GOOD FEET" << std::endl; }
``` 

This is the following crash:  
```
clang++ -o main main.cpp 
./main
GOOD HEAD
GOOD FEET
GOOD HEAD
NULL FEET
[1]    125526 segmentation fault (core dumped)  ./main
```
I don't think compiler versions or flags are much of the issue.

The segfault can be avoided by turning:  
`tr = from_depth_list(depth_list);`  

into:
```
tree<T> tr_new = from_depth_list(depth_list);
tr = tr_new;
```

Hm, trying to figure out if its my code, nlohmann::json, or tree invariants.

**Comment by kpeeters** [comment]
Sorry for the long wait, only just had time to look into this. It's a single line stupid typo in `tree.hh`: just before those lines in `operator=` in which you added debugging output, there is

     feet->prev_sibling=x.head->prev_sibling;

That's wrong of course, it should be

     feet->prev_sibling=x.feet->prev_sibling;

I'll fix this and push a new release. Thanks for spotting this!

**Comment by kpeeters** [comment]
Fixed the move constructor too now, thanks. 

Nice profile picture; brings back good memories ;-)
